insert into public.events (
  title,
  slug,
  description,
  sport,
  category,
  age_group,
  start_datetime,
  end_datetime,
  location,
  member_price,
  non_member_price,
  max_entries,
  status
) values
  (
    'Sunday Showdown Tennis Open',
    'sunday-showdown-tennis-open',
    'A weekly competitive tennis event for players ready for match play.',
    'tennis',
    'competitive',
    'open',
    '2026-06-07 07:00:00+02',
    '2026-06-07 10:30:00+02',
    'Kenmare Tennis Club',
    80,
    120,
    32,
    'published'
  ),
  (
    'Sunday Showdown Pickleball Open Mixed',
    'sunday-showdown-pickleball-open-mixed',
    'Open mixed pickleball play with simple pools and friendly finals.',
    'pickleball',
    'social',
    'open',
    '2026-06-14 08:00:00+02',
    '2026-06-14 11:00:00+02',
    'Kenmare Tennis Club',
    70,
    110,
    24,
    'published'
  ),
  (
    'Green Ball Primary School Event',
    'green-ball-primary-school-event',
    'A junior-friendly green ball event for primary school players.',
    'tennis',
    'junior',
    'green_ball',
    '2026-06-21 07:30:00+02',
    '2026-06-21 10:00:00+02',
    'Kenmare Tennis Club',
    60,
    90,
    20,
    'published'
  )
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  sport = excluded.sport,
  category = excluded.category,
  age_group = excluded.age_group,
  start_datetime = excluded.start_datetime,
  end_datetime = excluded.end_datetime,
  location = excluded.location,
  member_price = excluded.member_price,
  non_member_price = excluded.non_member_price,
  max_entries = excluded.max_entries,
  status = excluded.status,
  updated_at = now();
