import Link from "next/link";
import { notFound } from "next/navigation";
import { CollapsibleCard } from "@/components/collapsible-card";
import { MembershipPriceBreakdown, MembershipStatusChip } from "@/components/membership-ui";
import { CostIcon, EntriesIcon, MembershipIcon, StatusIcon } from "@/components/playr-icons";
import { StatusAlert } from "@/components/status-alert";
import { hasClubRMembershipCapability } from "@/lib/clubr";
import { formatMembershipMoney, loadMembershipSubscription, membershipStatusLabel } from "@/lib/club-memberships";
import { formatDate } from "@/lib/courtside-format";
import { ClubRPageFrame, getProtectedClubRPage } from "../../../clubr-shared";
import { recordManualMembershipPayment, setMembershipSubscriptionStatus } from "../../actions";

export const dynamic = "force-dynamic";
const inputClass = "mt-1 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm";

export default async function MembershipSubscriptionDetailPage({ params, searchParams }: { params: { subscriptionId: string }; searchParams?: { error?: string; message?: string } }) {
  const { content, context, venue } = await getProtectedClubRPage("clubr:memberships:subscriptions");
  if (content) return content;
  if (!context || !venue) return null;
  const [result, canManage, canRecordPayment] = await Promise.all([
    loadMembershipSubscription(context.supabase, params.subscriptionId),
    hasClubRMembershipCapability(context, "subscriptions_manage", venue.id),
    hasClubRMembershipCapability(context, "payments_record", venue.id)
  ]);
  const subscription = result.data;
  if (!subscription || subscription.venue_id !== venue.id) notFound();
  const nextPayment = subscription.billingSchedule.find((item) => item.status === "scheduled");

  return (
    <ClubRPageFrame context={context} subtitle="What is the status and structure of this membership?" title={subscription.plan?.name ?? subscription.price_snapshot.plan_name} venue={venue}>
      <StatusAlert className="mb-4" message={searchParams?.message === "payment_recorded" ? "Manual payment recorded. PlayR did not process this payment." : searchParams?.message ? "Membership updated." : null} tone="success" />
      <StatusAlert className="mb-4" message={searchParams?.error ? "The membership change could not be saved." : null} tone="error" />
      <Link className="mb-4 inline-block font-bold text-court-blue" href="/dashboard/clubr/memberships/subscriptions">Back to Subscriptions</Link>
      <section className="surface-card overflow-hidden"><div className="h-2 bg-court-teal" /><div className="p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="section-kicker">{subscription.venue?.name} · Version {subscription.plan?.version ?? subscription.price_snapshot.plan_version}</p><h2 className="mt-1 text-2xl font-black text-court-navy">{subscription.applicant ? `${subscription.applicant.first_name} ${subscription.applicant.last_name}` : "Club member"}</h2><p className="mt-2 text-sm text-slate-600">{formatDate(subscription.start_date)}{subscription.expiry_date ? ` to ${formatDate(subscription.expiry_date)}` : " · No fixed expiry"}</p></div><MembershipStatusChip status={subscription.status} /></div><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><div className="rounded bg-slate-50 p-3"><p className="text-xs font-black uppercase text-slate-500">Covered</p><p className="mt-1 font-black text-court-navy">{subscription.coveredMembers.length}</p></div><div className="rounded bg-slate-50 p-3"><p className="text-xs font-black uppercase text-slate-500">Accepted total</p><p className="mt-1 font-black text-court-navy">{formatMembershipMoney(subscription.accepted_total_cents, subscription.currency)}</p></div><div className="rounded bg-slate-50 p-3"><p className="text-xs font-black uppercase text-slate-500">Amount due</p><p className="mt-1 font-black text-court-navy">{formatMembershipMoney(subscription.amount_due_cents, subscription.currency)}</p></div><div className="rounded bg-slate-50 p-3"><p className="text-xs font-black uppercase text-slate-500">Next payment</p><p className="mt-1 font-black text-court-navy">{nextPayment ? formatDate(nextPayment.due_date) : "None"}</p></div></div></div></section>

      <div className="mt-5 grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><section className="surface-card p-4"><h2 className="flex items-center gap-2 font-black text-court-navy"><EntriesIcon size={17} /> Covered Members</h2><div className="mt-3 grid gap-2">{subscription.coveredMembers.map((member) => <Link className="rounded-lg border border-slate-200 p-3 transition hover:bg-court-mist" href={`/dashboard/clubr/members/${member.club_membership_id}`} key={member.id}><div className="flex items-start justify-between gap-3"><div><p className="font-black text-court-navy">{member.profile ? `${member.profile.first_name} ${member.profile.last_name}` : "Member"}</p><p className="mt-1 text-xs font-semibold text-slate-500">{member.plan?.name} · {member.member_role.replaceAll("_", " ")}</p></div><span className="ui-chip ui-chip-brand">{membershipStatusLabel(member.status)}</span></div></Link>)}</div></section><MembershipPriceBreakdown snapshot={subscription.price_snapshot} /></div>

      <CollapsibleCard className="mt-5" eyebrow="Payment ready" summary={`${subscription.billingSchedule.length} scheduled record${subscription.billingSchedule.length === 1 ? "" : "s"} · ${formatMembershipMoney(subscription.amount_due_cents, subscription.currency)} due`} title="Billing Schedule"><div className="grid gap-3">{subscription.billingSchedule.map((item) => <div className="rounded-lg border border-slate-200 p-3" key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black text-court-navy">Payment {item.sequence_number}</p><p className="mt-1 text-sm text-slate-600">Due {formatDate(item.due_date)} · {membershipStatusLabel(item.status)}</p></div><p className="font-black text-court-navy">{formatMembershipMoney(item.amount_cents, item.currency)}</p></div>{canRecordPayment && item.status === "scheduled" ? <details className="ui-collapsible mt-3 border-t border-slate-200 pt-3"><summary className="cursor-pointer text-sm font-black text-court-blue">Record Manual Payment</summary><form action={recordManualMembershipPayment} className="mt-3 grid gap-3 sm:grid-cols-2"><input name="venueId" type="hidden" value={venue.id} /><input name="subscriptionId" type="hidden" value={subscription.id} /><input name="billingScheduleId" type="hidden" value={item.id} /><label className="text-sm font-black text-court-navy">Amount (R)<input className={inputClass} defaultValue={((item.amount_cents - item.paid_amount_cents) / 100).toFixed(2)} max={(item.amount_cents - item.paid_amount_cents) / 100} min="0.01" name="amount" step="0.01" type="number" /></label><label className="text-sm font-black text-court-navy">Received on<input className={inputClass} defaultValue={new Date().toISOString().slice(0, 10)} name="receivedOn" type="date" /></label><label className="text-sm font-black text-court-navy">Method<select className={inputClass} name="paymentMethod"><option value="eft">EFT</option><option value="cash">Cash</option><option value="card_at_club">Card at club</option><option value="other">Other</option></select></label><label className="text-sm font-black text-court-navy">Reference<input className={inputClass} name="reference" required /></label><label className="text-sm font-black text-court-navy sm:col-span-2">Note<textarea className={inputClass} name="note" rows={2} /></label><label className="flex items-center gap-2 text-xs font-bold text-slate-600 sm:col-span-2"><input name="confirmed" required type="checkbox" /> Confirm this payment was received outside PlayR</label><button className="btn-primary sm:col-span-2" type="submit">Record Manual Payment</button><p className="text-xs font-semibold text-slate-500 sm:col-span-2">Recorded manually. PlayR did not process this payment.</p></form></details> : null}</div>)}{subscription.billingSchedule.length === 0 ? <div className="ui-empty-card">No payment is currently due.</div> : null}</div></CollapsibleCard>
      <CollapsibleCard className="mt-5" eyebrow="Audit" summary={`${subscription.manualPayments.length} manual payment record${subscription.manualPayments.length === 1 ? "" : "s"}`} title="Manual Payment Confirmations"><div className="grid gap-2">{subscription.manualPayments.map((payment) => <div className="rounded-lg border border-slate-200 p-3" key={payment.id}><div className="flex items-center justify-between gap-3"><div><p className="font-black text-court-navy">{formatMembershipMoney(payment.amount_cents, payment.currency)} · {membershipStatusLabel(payment.payment_method)}</p><p className="mt-1 text-xs text-slate-500">{formatDate(payment.received_on)} · Ref {payment.payment_reference}</p></div><span className="ui-chip ui-chip-warning">Manual</span></div></div>)}{subscription.manualPayments.length === 0 ? <div className="ui-empty-card">No manual payments recorded.</div> : null}</div></CollapsibleCard>
      {canManage && ["active", "paused", "expiring", "pending_activation"].includes(subscription.status) ? <section className="surface-card mt-5 p-4"><h2 className="flex items-center gap-2 font-black text-court-navy"><StatusIcon size={18} /> Membership Lifecycle</h2><p className="mt-1 text-sm text-slate-600">Changes update future access but do not silently delete confirmed bookings.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{subscription.status === "paused" ? <form action={setMembershipSubscriptionStatus} className="rounded-lg border border-slate-200 p-3"><input name="venueId" type="hidden" value={venue.id} /><input name="subscriptionId" type="hidden" value={subscription.id} /><input name="status" type="hidden" value="active" /><input name="confirmed" type="hidden" value="true" /><button className="btn-primary w-full" type="submit">Reactivate</button></form> : null}{subscription.status === "active" ? <form action={setMembershipSubscriptionStatus} className="rounded-lg border border-slate-200 p-3"><input name="venueId" type="hidden" value={venue.id} /><input name="subscriptionId" type="hidden" value={subscription.id} /><input name="status" type="hidden" value="paused" /><input className="w-full rounded border border-slate-300 px-3 py-2 text-sm" name="reason" placeholder="Pause reason" required /><label className="mt-2 flex items-center gap-2 text-xs font-bold text-slate-600"><input name="confirmed" required type="checkbox" /> Confirm</label><button className="btn-secondary mt-2 w-full" type="submit">Pause</button></form> : null}<form action={setMembershipSubscriptionStatus} className="rounded-lg border border-red-200 bg-red-50 p-3"><input name="venueId" type="hidden" value={venue.id} /><input name="subscriptionId" type="hidden" value={subscription.id} /><input name="status" type="hidden" value="cancelled" /><input className="w-full rounded border border-red-200 px-3 py-2 text-sm" name="reason" placeholder="Cancellation reason" required /><label className="mt-2 flex items-center gap-2 text-xs font-bold text-red-800"><input name="confirmed" required type="checkbox" /> Confirm cancellation</label><button className="btn-secondary mt-2 w-full border-red-300 text-red-800" type="submit">Cancel Membership</button></form></div></section> : null}
      <div className="mt-5 rounded-lg border border-court-teal/25 bg-court-mist p-4"><p className="flex items-center gap-2 font-black text-court-navy"><MembershipIcon size={18} /> Payment-ready, not payment processing</p><p className="mt-1 text-sm leading-6 text-slate-600">Invoices and schedule records are prepared for Phase 2.3. No checkout, provider transaction or settlement is created in this phase.</p></div>
    </ClubRPageFrame>
  );
}
