import Link from "next/link";
import { notFound } from "next/navigation";
import { CollapsibleCard } from "@/components/collapsible-card";
import { MembershipPriceBreakdown, MembershipStatusChip } from "@/components/membership-ui";
import { CostIcon, EntriesIcon, StatusIcon } from "@/components/playr-icons";
import { StatusAlert } from "@/components/status-alert";
import { hasClubRMembershipCapability } from "@/lib/clubr";
import { formatMembershipMoney, loadMembershipApplication, membershipTermLabel } from "@/lib/club-memberships";
import { formatDate } from "@/lib/courtside-format";
import { ClubRPageFrame, getProtectedClubRPage } from "../../../clubr-shared";
import { approveMembershipApplication, decideMembershipApplication } from "../../actions";

export const dynamic = "force-dynamic";

export default async function MembershipApplicationDetailPage({ params, searchParams }: { params: { applicationId: string }; searchParams?: { error?: string; message?: string } }) {
  const { content, context, venue } = await getProtectedClubRPage("clubr:memberships:applications");
  if (content) return content;
  if (!context || !venue) return null;
  const [applicationResult, canReview] = await Promise.all([loadMembershipApplication(context.supabase, params.applicationId), hasClubRMembershipCapability(context, "applications_review", venue.id)]);
  const application = applicationResult.data;
  if (!application || application.venue_id !== venue.id) notFound();
  const optionText = application.pricingOption ? membershipTermLabel({ commitment_months: application.price_snapshot.commitment_months ?? null, no_fixed_term: application.price_snapshot.no_fixed_term ?? false, payment_frequency: application.pricingOption.payment_frequency }) : application.price_snapshot.pricing_option_label;
  return (
    <ClubRPageFrame context={context} subtitle="Should this membership application be approved?" title="Review Application" venue={venue}>
      <StatusAlert className="mb-4" message={searchParams?.message ? "Application decision saved." : null} tone="success" />
      <StatusAlert className="mb-4" message={searchParams?.error === "price_changed" ? "The current plan price differs from the submitted snapshot. Request a correction before approval." : searchParams?.error ? "The application decision could not be saved." : null} tone="error" />
      <Link className="mb-4 inline-block font-bold text-court-blue" href="/dashboard/clubr/memberships/applications">Back to Applications</Link>
      <section className="surface-card p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="section-kicker">{application.plan?.name ?? application.price_snapshot.plan_name}</p><h2 className="mt-1 text-2xl font-black text-court-navy">{application.applicant ? `${application.applicant.first_name} ${application.applicant.last_name}` : "Applicant"}</h2><p className="mt-2 text-sm text-slate-600">Submitted {application.submitted_at ? formatDate(application.submitted_at) : "not submitted"} · Start {formatDate(application.requested_start_date)}</p></div><MembershipStatusChip status={application.status} /></div><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><div className="rounded bg-slate-50 p-3"><p className="text-xs font-black uppercase text-slate-500">Covered</p><p className="mt-1 font-black text-court-navy">{application.price_snapshot.members.length}</p></div><div className="rounded bg-slate-50 p-3"><p className="text-xs font-black uppercase text-slate-500">Total</p><p className="mt-1 font-black text-court-navy">{formatMembershipMoney(application.calculated_total_cents, application.currency)}</p></div><div className="rounded bg-slate-50 p-3 lg:col-span-2"><p className="text-xs font-black uppercase text-slate-500">Payment option</p><p className="mt-1 font-black text-court-navy">{optionText}</p></div></div></section>
      <div className="mt-5 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]"><section className="surface-card p-4"><h2 className="flex items-center gap-2 font-black text-court-navy"><EntriesIcon size={17} /> Covered Members</h2><div className="mt-3 grid gap-2">{application.price_snapshot.members.map((member) => <div className="rounded-lg border border-slate-200 p-3" key={member.profile_id}><div className="flex items-start justify-between gap-3"><div><p className="font-black text-court-navy">{member.profile_name}</p><p className="mt-1 text-xs font-semibold text-slate-500">{member.plan_name} · {member.member_role.replaceAll("_", " ")}</p></div><span className="ui-chip ui-chip-success">Eligible</span></div></div>)}</div></section><MembershipPriceBreakdown snapshot={application.price_snapshot} /></div>
      <CollapsibleCard className="mt-5" eyebrow="Application" summary="Terms, payer and applicant notes" title="Application Details"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded bg-slate-50 p-3"><p className="text-xs font-black uppercase text-slate-500">Responsible payer</p><p className="mt-1 font-black text-court-navy">{application.payer ? `${application.payer.first_name} ${application.payer.last_name}` : "Not available"}</p></div><div className="rounded bg-slate-50 p-3"><p className="text-xs font-black uppercase text-slate-500">Terms</p><p className="mt-1 font-black text-court-navy">{application.terms_accepted ? `Accepted ${application.terms_accepted_at ? formatDate(application.terms_accepted_at) : ""}` : "Not accepted"}</p></div><div className="rounded bg-slate-50 p-3 sm:col-span-2"><p className="text-xs font-black uppercase text-slate-500">Applicant note</p><p className="mt-1 text-sm text-slate-700">{application.applicant_notes ?? "No note provided."}</p></div></div></CollapsibleCard>
      {canReview && application.status === "pending_approval" ? <section className="surface-card mt-5 p-4"><div className="flex items-center gap-2"><StatusIcon className="text-court-teal" size={19} /><h2 className="font-black text-court-navy">Decision</h2></div><div className="mt-4 grid gap-4 lg:grid-cols-3"><form action={approveMembershipApplication} className="rounded-lg border border-emerald-200 bg-emerald-50 p-4"><input name="venueId" type="hidden" value={venue.id} /><input name="applicationId" type="hidden" value={application.id} /><p className="font-black text-emerald-900">Approve</p><p className="mt-1 text-sm text-emerald-800">Creates the subscription, covered records and billing schedule atomically.</p><label className="mt-3 flex items-center gap-2 text-xs font-bold text-emerald-900"><input name="confirmed" required type="checkbox" /> Confirm decision</label><button className="btn-primary mt-3 w-full" type="submit">Approve Application</button></form>{["request_correction", "decline"].map((decision) => <form action={decideMembershipApplication} className="rounded-lg border border-slate-200 p-4" key={decision}><input name="venueId" type="hidden" value={venue.id} /><input name="applicationId" type="hidden" value={application.id} /><input name="decision" type="hidden" value={decision} /><p className="font-black text-court-navy">{decision === "decline" ? "Decline" : "Request Correction"}</p><textarea className="mt-3 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" name="reason" placeholder="Reason required" required rows={2} /><label className="mt-2 flex items-center gap-2 text-xs font-bold text-slate-600"><input name="confirmed" required type="checkbox" /> Confirm decision</label><button className="btn-secondary mt-3 w-full" type="submit">{decision === "decline" ? "Decline Application" : "Request Correction"}</button></form>)}</div></section> : null}
      {application.status !== "pending_approval" ? <div className="mt-5 rounded-lg border border-slate-200 bg-slate-50 p-4"><p className="flex items-center gap-2 font-black text-court-navy"><CostIcon size={17} /> Decision complete</p><p className="mt-1 text-sm text-slate-600">{application.decline_reason ?? application.correction_message ?? "The application is preserved for historical review."}</p></div> : null}
    </ClubRPageFrame>
  );
}
